### PR TITLE
Update translation domains

### PR DESCRIPTION
**Pull request by AlexEven**
Apologies for the new branch, but it was quicker ^^

To avoid translation duplicates.

Thanks!

### CODE REVIEW

**Comment by AlexEven** [comment]
Can we merge this before 1.7.2.0 pleaaaase?

giphy-downsized

**Review by aleeks — APPROVED** [review]
Ok

**Comment by aleeks** [comment]
1.7.2.0 ! @maximebiloe do we have to make an other branch for 1.7.2.x modules ? ... omg

**Comment by maximebiloe** [comment]
@aleeks no, we just need to raise the min_compliancy up

**Comment by maximebiloe** [comment]
Thank you @AlexEven

**Pull request merged**
